spring:
  cloud:
    gateway:
      routes:
        - id: patient-service-route
          uri: http://patient-service:8081
          predicates:
            - Path=/api/v1/patients/**
          filters:
              - JwtAuthentication

        - id: auth-service-route
          uri: http://auth-service:8084
          predicates:
            - Path=/api/v1/auth/**

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.cloud.gateway: TRACE
    reactor.netty.http.client: DEBUG
    reactor.netty.http.server: DEBUG