spring.application.name=patient-service
#grpc.billing-service.host=localhost
#grpc.billing-service.port=9091
# H2 (in-memory) datasource - development settings
#spring.datasource.url=jdbc:h2:mem:patientsdb;
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=password

## JPA / Hibernate
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

# H2 Console
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#spring.h2.console.settings.web-allow-others=true


